import heapq

class Nodo:
    def __init__(self, nombre, conexiones=None, accesible=True):
        self.nombre = nombre
        self.conexiones = conexiones if conexiones else {}
        self.accesible = accesible

    def agregar_conexion(self, otro_nodo, costo, ruta):
        self.conexiones[otro_nodo] = (costo, ruta)

class Grafo:
    def __init__(self):
        self.nodos = {}

    def agregar_nodo(self, nombre, accesible=True):
        if nombre not in self.nodos:
            self.nodos[nombre] = Nodo(nombre, accesible=accesible)

    def agregar_conexion(self, desde, hacia, costo, ruta):
        if desde in self.nodos and hacia in self.nodos:
            self.nodos[desde].agregar_conexion(self.nodos[hacia], costo, ruta)

    def obtener_nodo(self, nombre):
        return self.nodos.get(nombre, None)

def a_estrella(grafo, inicio, fin):
    cola_prioridad = []
    heapq.heappush(cola_prioridad, (0, inicio))  # (costo, nodo)
    costos = {inicio: 0}
    padres = {inicio: (None, None)}  # (padre, ruta)

    while cola_prioridad:
        costo_actual, nodo_actual = heapq.heappop(cola_prioridad)

        if nodo_actual == fin:
            ruta = []
            rutas_nombres = []
            while nodo_actual:
                ruta.append(nodo_actual)
                nodo_actual, ruta_nombre = padres[nodo_actual]
                if ruta_nombre:
                    rutas_nombres.append(ruta_nombre)
            return ruta[::-1], costos[fin], rutas_nombres[::-1]

        for vecino, (costo, ruta_nombre) in grafo.obtener_nodo(nodo_actual).conexiones.items():
            nuevo_costo = costo_actual + costo
            if vecino.nombre not in costos or nuevo_costo < costos[vecino.nombre]:
                costos[vecino.nombre] = nuevo_costo
                prioridad = nuevo_costo
                heapq.heappush(cola_prioridad, (prioridad, vecino.nombre))
                padres[vecino.nombre] = (nodo_actual, ruta_nombre)

    return None, None, None

# Crear grafo y estaciones
grafo = Grafo()
rutas = [
    ("Universidades", "Centro Memoria", 5, "1"),
    ("Centro Memoria", "Concejo de Bogotá", 5, "1"),
    ("Concejo de Bogotá", "Ciudad Universitaria", 5, "1"),
    ("Ciudad Universitaria", "Corferias", 5, "1"),
    ("Corferias", "Quinta Paredes", 5, "1"),
    ("Quinta Paredes", "Gobernación", 5, "1"),
    ("Gobernación", "CAN", 5, "1"),
    ("CAN", "El Tiempo", 5, "1"),
    ("El Tiempo", "Avenida Rojas", 5, "1"),
    ("Avenida Rojas", "Normandía", 5, "1"),
    ("Normandía", "Modelia", 5, "1"),
    ("Modelia", "Portal Eldorado", 5, "1"),

    ("Portal Eldorado", "Modelia", 5, "1"),
    ("Modelia", "Normandía", 5, "1"),
    ("Normandía", "Avenida Rojas", 5, "1"),
    ("Avenida Rojas", "El Tiempo", 5, "1"),
    ("El Tiempo", "CAN", 5, "1"),
    ("CAN", "Gobernación", 5, "1"),
    ("Gobernación", "Quinta Paredes", 5, "1"),
    ("Quinta Paredes", "Corferias", 5, "1"),
    ("Corferias", "Ciudad Universitaria", 5, "1"),
    ("Ciudad Universitaria", "Concejo de Bogotá", 5, "1"),
    ("Concejo de Bogotá", "Centro Memoria", 5, "1"),
    ("Centro Memoria", "Universidades", 5, "1"),

    ("Museo Nacional", "San Diego", 3, "2"),
    ("San Diego", "Las Nieves", 3, "2"),
    ("Las Nieves", "San Victorino", 3, "2"),
    ("San Victorino", "Bicentenario", 3, "2"),
    ("Bicentenario", "San Bernardo", 3, "2"),
    ("San Bernardo", "Policarpa", 3, "2"),
    ("Policarpa", "Ciudad Jardín", 3, "2"),
    ("Ciudad Jardín", "Avenida Primero de Mayo", 3, "2"),
    ("Avenida Primero de Mayo", "Country Sur", 3, "2"),
    ("Country Sur", "Portal 20 de Julio", 3, "2"),

    ("Portal 20 de Julio", "Country Sur", 3, "2"),
    ("Country Sur", "Avenida Primero de Mayo", 3, "2"),
    ("Avenida Primero de Mayo", "Ciudad Jardín", 3, "2"),
    ("Ciudad Jardín", "Policarpa", 3, "2"),
    ("Policarpa", "San Bernardo", 3, "2"),
    ("San Bernardo", "Bicentenario", 3, "2"),
    ("Bicentenario", "San Victorino", 3, "2"),
    ("San Victorino", "Las Nieves", 3, "2"),
    ("Las Nieves", "San Diego", 3, "2"),
    ("San Diego", "Museo Nacional", 3, "2"),

    ("Corferias", "Ciudad Universitaria", 5, "3"),
    ("Ciudad Universitaria", "Concejo de Bogotá", 5, "3"),
    ("Concejo de Bogotá", "Centro Memoria", 5, "3"),
    ("Centro Memoria", "Calle 22", 5, "3"),
    ("Calle 22", "Calle 19", 5, "3"),
    ("Calle 19", "Avenida Jiménez", 5, "3"),
    ("Avenida Jiménez", "Tercer Milenio", 5, "3"),
    ("Tercer Milenio", "Hospital", 5, "3"),
    ("Hospital", "Hortúa", 5, "3"),
    ("Hortúa", "Nariño", 5, "3"),
    ("Nariño", "Fucha", 5, "3"),
    ("Fucha", "Restrepo", 5, "3"),
    ("Restrepo", "Olaya", 5, "3"),
    ("Olaya", "Quiroga", 5, "3"),
    ("Quiroga", "Calle 40 Sur", 5, "3"),
    ("Calle 40 Sur", "Santa Lucía", 5, "3"),
    ("Santa Lucía", "Biblioteca", 5, "3"),
    ("Biblioteca", "Parque", 5, "3"),
    ("Parque", "Portal Tunal", 5, "3"),

    ("Portal Tunal", "Parque", 5, "3"),
    ("Parque", "Biblioteca", 5, "3"),
    ("Biblioteca", "Santa Lucía", 5, "3"),
    ("Santa Lucía", "Calle 40 Sur", 5, "3"),
    ("Calle 40 Sur", "Quiroga", 5, "3"),
    ("Quiroga", "Olaya", 5, "3"),
    ("Olaya", "Restrepo", 5, "3"),
    ("Restrepo", "Fucha", 5, "3"),
    ("Fucha", "Nariño", 5, "3"),
    ("Nariño", "Hortúa", 5, "3"),
    ("Hortúa", "Hospital", 5, "3"),
    ("Hospital", "Tercer Milenio", 5, "3"),
    ("Tercer Milenio", "Avenida Jiménez", 5, "3"),
    ("Avenida Jiménez", "Calle 19", 5, "3"),
    ("Calle 19", "Calle 22", 5, "3"),
    ("Calle 22", "Centro Memoria", 5, "3"),
    ("Centro Memoria", "Concejo de Bogotá", 5, "3"),
    ("Concejo de Bogotá", "Ciudad Universitaria", 5, "3"),
    ("Ciudad Universitaria", "Corferias", 5, "3"),

    ("Héroes", "Polo", 3, "4"),
    ("Polo", "Escuela Militar", 3, "4"),
    ("Escuela Militar", "NQS Calle 75", 3, "4"),
    ("NQS Calle 75", "Avenida Chile", 3, "4"),
    ("Avenida Chile", "7 de Agosto", 3, "4"),
    ("7 de Agosto", "Movistar Arena", 3, "4"),
    ("Movistar Arena", "Campín", 3, "4"),
    ("Campín", "Universidad Nacional", 3, "4"),
    ("Universidad Nacional", "Avenida Eldorado", 3, "4"),
    ("Avenida Eldorado", "CAD", 3, "4"),
    ("CAD", "Paloquemao", 3, "4"),
    ("Paloquemao", "Ricaurte", 3, "4"),
    ("Ricaurte", "Comuneros", 3, "4"),
    ("Comuneros", "Santa Isabel", 3, "4"),
    ("Santa Isabel", "NQS Calle 30 Sur", 3, "4"),
    ("NQS Calle 30 Sur", "NQS Calle 38 A Sur", 3, "4"),
    ("NQS Calle 38 A Sur", "General Santander", 3, "4"),
    ("General Santander", "Alquería", 3, "4"),
    ("Alquería", "Venecia", 3, "4"),
    ("Venecia", "Sevillana", 3, "4"),
    ("Sevillana", "Madelena", 3, "4"),
    ("Madelena", "Perdomo", 3, "4"),
    ("Perdomo", "Portal Sur", 3, "4"),

    ("Portal Sur", "Perdomo", 3, "4"),
    ("Perdomo", "Madelena", 3, "4"),
    ("Madelena", "Sevillana", 3, "4"),
    ("Sevillana", "Venecia", 3, "4"),
    ("Venecia", "Alquería", 3, "4"),
    ("Alquería", "General Santander", 3, "4"),
    ("General Santander", "NQS Calle 38 A Sur", 3, "4"),
    ("NQS Calle 38 A Sur", "NQS Calle 30 Sur", 3, "4"),
    ("NQS Calle 30 Sur", "Santa Isabel", 3, "4"),
    ("Santa Isabel", "Comuneros", 3, "4"),
    ("Comuneros", "Ricaurte", 3, "4"),
    ("Ricaurte", "Paloquemao", 3, "4"),
    ("Paloquemao", "CAD", 3, "4"),
    ("CAD", "Avenida Eldorado", 3, "4"),
    ("Avenida Eldorado", "Universidad Nacional", 3, "4"),
    ("Universidad Nacional", "Campín", 3, "4"),
    ("Campín", "Movistar Arena", 3, "4"),
    ("Movistar Arena", "7 de Agosto", 3, "4"),
    ("7 de Agosto", "Avenida Chile", 3, "4"),
    ("Avenida Chile", "NQS Calle 75", 3, "4"),
    ("NQS Calle 75", "Escuela Militar", 3, "4"),
    ("Escuela Militar", "Polo", 3, "4"),
    ("Polo", "Héroes", 3, "4"),

    ("Calle 22", "Calle 19", 3, "5"),
    ("Calle 19", "Avenida Jiménez", 3, "5"),
    ("Avenida Jiménez", "De La Sabana", 3, "5"),
    ("De La Sabana", "San Façon Carrera 22", 3, "5"),
    ("San Façon Carrera 22", "Ricaurte", 3, "5"),
    ("Ricaurte", "CDS Carrera 32", 3, "5"),
    ("CDS Carrera 32", "Zona Industrial", 3, "5"),
    ("Zona Industrial", "Carrera 43", 3, "5"),
    ("Carrera 43", "Puente Aranda", 3, "5"),
    ("Puente Aranda", "Distrito Grafiti", 3, "5"),
    ("Distrito Grafiti", "Pradera", 3, "5"),
    ("Pradera", "Marsella", 3, "5"),
    ("Marsella", "Américas - Avenida Boyacá", 3, "5"),
    ("Américas - Avenida Boyacá", "Mandalay", 3, "5"),
    ("Mandalay", "Banderas", 3, "5"),
    ("Banderas", "Transversal 86", 3, "5"),
    ("Transversal 86", "Biblioteca Tintal", 3, "5"),
    ("Biblioteca Tintal", "Portal Américas", 3, "5"),

    ("Portal Américas", "Biblioteca Tintal", 4, "5"),
    ("Biblioteca Tintal", "Transversal 86", 4, "5"),
    ("Transversal 86", "Banderas", 4, "5"),
    ("Banderas", "Mandalay", 4, "5"),
    ("Mandalay", "Américas - Avenida Boyacá", 4, "5"),
    ("Américas - Avenida Boyacá", "Marsella", 4, "5"),
    ("Marsella", "Pradera", 4, "5"),
    ("Pradera", "Distrito Grafiti", 4, "5"),
    ("Distrito Grafiti", "Puente Aranda", 4, "5"),
    ("Puente Aranda", "Carrera 43", 4, "5"),
    ("Carrera 43", "Zona Industrial", 4, "5"),
    ("Zona Industrial", "CDS Carrera 32", 4, "5"),
    ("CDS Carrera 32", "Ricaurte", 4, "5"),
    ("Ricaurte", "San Façon Carrera 22", 4, "5"),
    ("San Façon Carrera 22", "De La Sabana", 4, "5"),
    ("De La Sabana", "Avenida Jiménez", 4, "5"),
    ("Avenida Jiménez", "Calle 19", 4, "5"),
    ("Calle 19", "Calle 22", 4, "5"),

    ("Portal 80", "Quirigua", 3, "6"),
    ("Quirigua", "Carrera 90", 3, "6"),
    ("Carrera 90", "Avenida Cali", 3, "6"),
    ("Avenida Cali", "Granja - Carrera 77", 3, "6"),
    ("Granja - Carrera 77", "Minuto de Dios", 3, "6"),
    ("Minuto de Dios", "Boyacá", 3, "6"),
    ("Boyacá", "Ferias", 3, "6"),
    ("Ferias", "Avenida 68", 3, "6"),
    ("Avenida 68", "Carrera 53", 3, "6"),
    ("Carrera 53", "Carrera 47", 3, "6"),
    ("Carrera 47", "Escuela Militar", 3, "6"),
    ("Escuela Militar", "Polo", 3, "6"),
    ("Polo", "Calle 76", 3, "6"),
    ("Calle 76", "Flores", 3, "6"),
    ("Flores", "Calle 57", 3, "6"),
    ("Calle 57", "Calle 45", 3, "6"),
    ("Calle 45", "Avenida 39", 3, "6"),
    ("Avenida 39", "Calle 34", 3, "6"),
    ("Calle 34", "Universidades", 3, "6"),

    ("Universidades", "Calle 34", 3, "6"),
    ("Calle 34", "Avenida 39", 3, "6"),
    ("Avenida 39", "Calle 45", 3, "6"),
    ("Calle 45", "Calle 57", 3, "6"),
    ("Calle 57", "Flores", 3, "6"),
    ("Flores", "Calle 76", 3, "6"),
    ("Calle 76", "Polo", 3, "6"),
    ("Polo", "Escuela Militar", 3, "6"),
    ("Escuela Militar", "Carrera 47", 3, "6"),
    ("Carrera 47", "Carrera 53", 3, "6"),
    ("Carrera 53", "Avenida 68", 3, "6"),
    ("Avenida 68", "Ferias", 3, "6"),
    ("Ferias", "Boyacá", 3, "6"),
    ("Boyacá", "Minuto de Dios", 3, "6"),
    ("Minuto de Dios", "Granja - Carrera 77", 3, "6"),
    ("Granja - Carrera 77", "Avenida Cali", 3, "6"),
    ("Avenida Cali", "Carrera 90", 3, "6"),
    ("Carrera 90", "Quirigua", 3, "6"),
    ("Quirigua", "Portal 80", 3, "6"),

    ("Portal Suba", "La Campiña", 3, "7"),
    ("La Campiña", "Suba - Tv. 91", 3, "7"),
    ("Suba - Tv. 91", "21 Ángeles", 3, "7"),
    ("21 Ángeles", "Gratamira", 3, "7"),
    ("Gratamira", "Suba Av. Boyacá", 3, "7"),
    ("Suba Av. Boyacá", "Niza Calle 127", 3, "7"),
    ("Niza Calle 127", "Humedal Córdoba", 3, "7"),
    ("Humedal Córdoba", "Av. Suba Calle 116", 3, "7"),
    ("Av. Suba Calle 116", "Puente Largo", 3, "7"),
    ("Puente Largo", "Suba Calle 100", 3, "7"),
    ("Suba Calle 100", "Suba Calle 95", 3, "7"),
    ("Suba Calle 95", "Rionegro", 3, "7"),
    ("Rionegro", "San Martín", 3, "7"),
    ("San Martín", "Escuela Militar", 3, "7"),
    ("Escuela Militar", "Polo", 3, "7"),

    ("Polo", "Escuela Militar", 3, "7"),
    ("Escuela Militar", "San Martín", 3, "7"),
    ("San Martín", "Rionegro", 3, "7"),
    ("Rionegro", "Suba Calle 95", 3, "7"),
    ("Suba Calle 95", "Suba Calle 100", 3, "7"),
    ("Suba Calle 100", "Puente Largo", 3, "7"),
    ("Puente Largo", "Av. Suba Calle 116", 3, "7"),
    ("Av. Suba Calle 116", "Humedal Córdoba", 3, "7"),
    ("Humedal Córdoba", "Niza Calle 127", 3, "7"),
    ("Niza Calle 127", "Suba Av. Boyacá", 3, "7"),
    ("Suba Av. Boyacá", "Gratamira", 3, "7"),
    ("Gratamira", "21 Ángeles", 3, "7"),
    ("21 Ángeles", "Suba - Tv. 91", 3, "7"),
    ("Suba - Tv. 91", "La Campiña", 3, "7"),
    ("La Campiña", "Portal Suba", 3, "7"),

    ("Terminal", "Calle 187", 2, "8"),
    ("Calle 187", "Portal Norte", 2, "8"),
    ("Portal Norte", "Toberín", 2, "8"),
    ("Toberín", "Calle 161", 2, "8"),
    ("Calle 161", "Mazurén", 2, "8"),
    ("Mazurén", "Calle 146", 2, "8"),
    ("Calle 146", "Calle 142", 2, "8"),
    ("Calle 142", "Alcalá", 2, "8"),
    ("Alcalá", "Prado", 2, "8"),
    ("Prado", "Calle 127", 2, "8"),
    ("Calle 127", "Pepe Sierra", 2, "8"),
    ("Pepe Sierra", "Calle 106", 2, "8"),
    ("Calle 106", "Calle 100", 2, "8"),
    ("Calle 100", "Virrey", 2, "8"),
    ("Virrey", "Calle 85", 2, "8"),
    ("Calle 85", "Héroes", 2, "8"),
    ("Héroes", "Calle 76", 2, "8"),
    ("Calle 76", "Flores", 2, "8"),
    ("Flores", "Calle 57", 2, "8"),
    ("Calle 57", "Calle 45", 2, "8"),
    ("Calle 45", "Avenida 39", 2, "8"),
    ("Avenida 39", "Calle 34", 2, "8"),
    ("Calle 34", "Calle 22", 2, "8"),
    ("Calle 22", "Calle 19", 2, "8"),
    ("Calle 19", "Avenida Jiménez", 2, "8"),
    ("Avenida Jiménez", "Tercer Milenio", 2, "8"),
    ("Tercer Milenio", "Tygya - San José", 2, "8"),
    ("Tygya - San José", "Guatoque - Veraguas", 2, "8"),

    ("Guatoque - Veraguas", "Tygya - San José", 2, "8"),
    ("Tygya - San José", "Tercer Milenio", 2, "8"),
    ("Tercer Milenio", "Avenida Jiménez", 2, "8"),
    ("Avenida Jiménez", "Calle 19", 2, "8"),
    ("Calle 19", "Calle 22", 2, "8"),
    ("Calle 22", "Calle 34", 2, "8"),
    ("Calle 34", "Avenida 39", 2, "8"),
    ("Avenida 39", "Calle 45", 2, "8"),
    ("Calle 45", "Calle 57", 2, "8"),
    ("Calle 57", "Flores", 2, "8"),
    ("Flores", "Calle 76", 2, "8"),
    ("Calle 76", "Héroes", 2, "8"),
    ("Héroes", "Calle 85", 2, "8"),
    ("Calle 85", "Virrey", 2, "8"),
    ("Virrey", "Calle 100", 2, "8"),
    ("Calle 100", "Calle 106", 2, "8"),
    ("Calle 106", "Pepe Sierra", 2, "8"),
    ("Pepe Sierra", "Calle 127", 2, "8"),
    ("Calle 127", "Prado", 2, "8"),
    ("Prado", "Alcalá", 2, "8"),
    ("Alcalá", "Calle 142", 2, "8"),
    ("Calle 142", "Calle 146", 2, "8"),
    ("Calle 146", "Mazurén", 2, "8"),
    ("Mazurén", "Calle 161", 2, "8"),
    ("Calle 161", "Toberín", 2, "8"),
    ("Toberín", "Portal Norte", 2, "8"),
    ("Portal Norte", "Calle 187", 2, "8"),
    ("Calle 187", "Terminal", 2, "8"),

    ("Portal Sur", "Perdomo", 4, "A52"),
    ("Perdomo", "Madelena", 4, "A52"),
    ("Madelena", "Venecia", 4, "A52"),
    ("Venecia", "Alquería", 4, "A52"),
    ("Alquería", "General Santander", 4, "A52"),
    ("General Santander", "NQS Calle 30 Sur", 4, "A52"),
    ("NQS Calle 30 Sur", "Santa Isabel", 4, "A52"),
    ("Santa Isabel", "Calle 76", 4, "A52"),
    ("Calle 76", "Flores", 4, "A52"),

    ("Portal Américas", "Transversal 86", 5, "A60"),
    ("Transversal 86", "Banderas", 5, "A60"),
    ("Banderas", "Carrera 43", 5, "A60"),
    ("Carrera 43", "Ricaurte", 5, "A60"),
    ("Ricaurte", "De La Sabana", 5, "A60"),
    ("De La Sabana", "Calle 34", 5, "A60"),
    ("Calle 34", "Calle 45", 5, "A60"),
    ("Calle 45", "Calle 76", 5, "A60"),

    ("Portal Américas", "Banderas", 7, "A61"),
    ("Banderas", "Marsella", 7, "A61"),
    ("Marsella", "CDS Carrera 32", 7, "A61"),
    ("CDS Carrera 32", "Calle 19", 7, "A61"),
    ("Calle 19", "Avenida 39", 7, "A61"),
    ("Avenida 39", "Flores", 7, "A61"),
    ("Flores", "Polo", 7, "A61"),

    ("Portal 80", "Carrera 90", 3, "B10"),
    ("Carrera 90", "Avenida Cali", 3, "B10"),
    ("Avenida Cali", "Granja - Carrera 77", 3, "B10"),
    ("Granja - Carrera 77", "Boyacá", 3, "B10"),
    ("Boyacá", "Avenida 68", 3, "B10"),
    ("Avenida 68", "Carrera 53", 3, "B10"),
    ("Carrera 53", "Carrera 47", 3, "B10"),
    ("Carrera 47", "Calle 85", 3, "B10"),
    ("Calle 85", "Calle 100", 3, "B10"),
    ("Calle 100", "Alcalá", 3, "B10"),
    ("Alcalá", "Calle 146", 3, "B10"),
    ("Calle 146", "Toberín", 3, "B10"),
    ("Toberín", "Portal Norte", 3, "B10"),

    ("Portal Sur", "Madelena", 3, "B11"),
    ("Madelena", "Alquería", 3, "B11"),
    ("Alquería", "NQS Calle 30 Sur", 3, "B11"),
    ("NQS Calle 30 Sur", "Santa Isabel", 3, "B11"),
    ("Santa Isabel", "Ricaurte", 3, "B11"),
    ("Ricaurte", "Paloquemao", 3, "B11"),
    ("Paloquemao", "Campín", 3, "B11"),
    ("Campín", "Escuela Militar", 3, "B11"),
    ("Escuela Militar", "Héroes", 3, "B11"),
    ("Héroes", "Calle 85", 3, "B11"),
    ("Calle 85", "Virrey", 3, "B11"),
    ("Virrey", "Calle 106", 3, "B11"),
    ("Calle 106", "Pepe Sierra", 3, "B11"),
    ("Pepe Sierra", "Calle 146", 3, "B11"),
    ("Calle 146", "Toberín", 3, "B11"),
    ("Toberín", "Calle 187", 3, "B11"),
    ("Calle 187", "Terminal", 3, "B11"),

    ("Portal Sur", "Perdomo", 3, "B12"),
    ("Perdomo", "General Santander", 3, "B12"),
    ("General Santander", "Comuneros", 3, "B12"),
    ("Comuneros", "Ricaurte", 3, "B12"),
    ("Ricaurte", "Avenida Eldorado", 3, "B12"),
    ("Avenida Eldorado", "Universidad Nacional", 3, "B12"),
    ("Universidad Nacional", "7 de Agosto", 3, "B12"),
    ("7 de Agosto", "NQS Calle 75", 3, "B12"),
    ("NQS Calle 75", "La Castellana", 3, "B12"),
    ("La Castellana", "Calle 100", 3, "B12"),
    ("Calle 100", "Calle 127", 3, "B12"),
    ("Calle 127", "Prado", 3, "B12"),
    ("Prado", "Calle 142", 3, "B12"),
    ("Calle 142", "Toberín", 3, "B12"),
    ("Toberín", "Portal Norte", 3, "B12"),

    ("Portal Norte", "Calle 161", 6, "B13"),
    ("Calle 161", "Mazurén", 6, "B13"),
    ("Mazurén", "Calle 146", 6, "B13"),
    ("Calle 146", "Calle 142", 6, "B13"),
    ("Calle 142", "Calle 106", 6, "B13"),
    ("Calle 106", "Calle 85", 6, "B13"),
    ("Calle 85", "Flores", 6, "B13"),
    ("Flores", "Avenida 39", 6, "B13"),
    ("Avenida 39", "Calle 22", 6, "B13"),
    ("Calle 22", "Tercer Milenio", 6, "B13"),
    ("Tercer Milenio", "Hortúa", 6, "B13"),
    ("Hortúa", "Restrepo", 6, "B13"),
    ("Restrepo", "Quiroga", 6, "B13"),
    ("Quiroga", "Biblioteca", 6, "B13"),
    ("Biblioteca", "Portal Tunal", 6, "B13"),

    ("Portal Eldorado", "Modelia", 4, "B16"),
    ("Modelia", "Avenida Rojas", 4, "B16"),
    ("Avenida Rojas", "El Tiempo", 4, "B16"),
    ("El Tiempo", "Salitre - El Greco", 4, "B16"),
    ("Salitre - El Greco", "CAN", 4, "B16"),
    ("CAN", "Quinta Paredes", 4, "B16"),
    ("Quinta Paredes", "Corferias", 4, "B16"),
    ("Corferias", "Avenida Eldorado", 4, "B16"),
    ("Avenida Eldorado", "Avenida Chile", 4, "B16"),
    ("Avenida Chile", "Pepe Sierra", 4, "B16"),
    ("Pepe Sierra", "Alcalá", 4, "B16"),
    ("Alcalá", "Toberín", 4, "B16"),
    ("Toberín", "Calle 187", 4, "B16"),
    ("Calle 187", "Terminal", 4, "B16"),

    ("Portal 20 de Julio", "Country Sur", 4, "B18"),
    ("Country Sur", "Avenida Primero de Mayo", 4, "B18"),
    ("Avenida Primero de Mayo", "San Bernardo", 4, "B18"),
    ("San Bernardo", "Bicentenario", 4, "B18"),
    ("Bicentenario", "Tercer Milenio", 4, "B18"),
    ("Tercer Milenio", "Calle 34", 4, "B18"),
    ("Calle 34", "Calle 45", 4, "B18"),
    ("Calle 45", "Virrey", 4, "B18"),
    ("Virrey", "Pepe Sierra", 4, "B18"),
    ("Pepe Sierra", "Calle 127", 4, "B18"),
    ("Calle 127", "Alcalá", 4, "B18"),
    ("Alcalá", "Calle 187", 4, "B18"),
    ("Calle 187", "Terminal", 4, "B18"),

    ("Portal Eldorado", "Avenida Rojas", 4, "B23"),
    ("Avenida Rojas", "El Tiempo", 4, "B23"),
    ("El Tiempo", "Salitre - El Greco", 4, "B23"),
    ("Salitre - El Greco", "CAN", 4, "B23"),
    ("CAN", "Gobernación", 4, "B23"),
    ("Gobernación", "Ciudad Universitaria", 4, "B23"),
    ("Ciudad Universitaria", "Concejo de Bogotá", 4, "B23"),
    ("Concejo de Bogotá", "Calle 45", 4, "B23"),
    ("Calle 45", "Calle 57", 4, "B23"),
    ("Calle 57", "Calle 85", 4, "B23"),
    ("Calle 85", "Calle 127", 4, "B23"),
    ("Calle 127", "Prado", 4, "B23"),
    ("Prado", "Alcalá", 4, "B23"),

    ("Portal Américas", "Transversal 86", 4, "B26"),
    ("Transversal 86", "Banderas", 4, "B26"),
    ("Banderas", "Mandalay", 4, "B26"),
    ("Mandalay", "Américas - Avenida Boyacá", 4, "B26"),
    ("Américas - Avenida Boyacá", "Héroes", 4, "B26"),
    ("Héroes", "Calle 85", 4, "B26"),
    ("Calle 85", "Virrey", 4, "B26"),
    ("Virrey", "Calle 100", 4, "B26"),
    ("Calle 100", "Calle 127", 4, "B26"),
    ("Calle 127", "Alcalá", 4, "B26"),

    ("Portal Tunal", "Calle 40 Sur", 5, "B27"),
    ("Calle 40 Sur", "Avenida Jiménez", 5, "B27"),
    ("Avenida Jiménez", "Calle 34", 5, "B27"),
    ("Calle 34", "Calle 76", 5, "B27"),
    ("Calle 76", "Héroes", 5, "B27"),
    ("Héroes", "Calle 85", 5, "B27"),
    ("Calle 85", "Virrey", 5, "B27"),
    ("Virrey", "Calle 100", 5, "B27"),
    ("Calle 100", "Toberín", 5, "B27"),
    ("Toberín", "Portal Norte", 5, "B27"),

    ("Portal Américas", "Biblioteca Tintal", 6, "B28"),
    ("Biblioteca Tintal", "Banderas", 6, "B28"),
    ("Banderas", "Marsella", 6, "B28"),
    ("Marsella", "Zona Industrial", 6, "B28"),
    ("Zona Industrial", "CDS Carrera 32", 6, "B28"),
    ("CDS Carrera 32", "La Castellana", 6, "B28"),
    ("La Castellana", "Calle 106", 6, "B28"),
    ("Calle 106", "Pepe Sierra", 6, "B28"),
    ("Pepe Sierra", "Prado", 6, "B28"),
    ("Prado", "Calle 146", 6, "B28"),
    ("Calle 146", "Calle 161", 6, "B28"),
    ("Calle 161", "Portal Norte", 6, "B28"),

    ("San Mateo", "Terreros", 5, "B46"),
    ("Terreros", "León XIII", 5, "B46"),
    ("León XIII", "La Despensa", 5, "B46"),
    ("La Despensa", "Estación Bosa", 5, "B46"),
    ("Estación Bosa", "Calle 100", 5, "B46"),
    ("Calle 100", "Alcalá", 5, "B46"),
    ("Alcalá", "Toberín", 5, "B46"),
    ("Toberín", "Portal Norte", 5, "B46"),

    ("Portal Suba", "La Campiña", 3, "B50"),
    ("La Campiña", "Suba - Tv. 91", 3, "B50"),
    ("Suba - Tv. 91", "21 Ángeles", 3, "B50"),
    ("21 Ángeles", "Av. Suba Calle 116", 3, "B50"),
    ("Av. Suba Calle 116", "Puente Largo", 3, "B50"),
    ("Puente Largo", "Rionegro", 3, "B50"),
    ("Rionegro", "Escuela Militar", 3, "B50"),
    ("Escuela Militar", "Héroes", 3, "B50"),
    ("Héroes", "Calle 85", 3, "B50"),
    ("Calle 85", "Virrey", 3, "B50"),
    ("Virrey", "Calle 142", 3, "B50"),
    ("Calle 142", "Calle 161", 3, "B50"),

    ("Portal 80", "Quirigua", 2, "B55"),
    ("Quirigua", "Avenida Cali", 2, "B55"),
    ("Avenida Cali", "Granja - Carrera 77", 2, "B55"),
    ("Granja - Carrera 77", "Minuto de Dios", 2, "B55"),
    ("Minuto de Dios", "Ferias", 2, "B55"),
    ("Ferias", "Polo", 2, "B55"),
    ("Polo", "Héroes", 2, "B55"),
    ("Héroes", "Virrey", 2, "B55"),
    ("Virrey", "Calle 106", 2, "B55"),
    ("Calle 106", "Pepe Sierra", 2, "B55"),
    ("Pepe Sierra", "Prado", 2, "B55"),
    ("Prado", "Calle 142", 2, "B55"),
    ("Calle 142", "Calle 161", 2, "B55"),
    ("Calle 161", "Toberín", 2, "B55"),

    ("Portal Usme", "Molinos", 5, "B72"),
    ("Molinos", "Socorro", 5, "B72"),
    ("Socorro", "Olaya", 5, "B72"),
    ("Olaya", "Fucha", 5, "B72"),
    ("Fucha", "Nariño", 5, "B72"),
    ("Nariño", "Hospital", 5, "B72"),
    ("Hospital", "Tygya - San José", 5, "B72"),
    ("Tygya - San José", "Paloquemao", 5, "B72"),
    ("Paloquemao", "Movistar Arena", 5, "B72"),
    ("Movistar Arena", "Avenida Chile", 5, "B72"),
    ("Avenida Chile", "La Castellana", 5, "B72"),
    ("La Castellana", "Pepe Sierra", 5, "B72"),
    ("Pepe Sierra", "Alcalá", 5, "B72"),
    ("Alcalá", "Mazurén", 5, "B72"),
    ("Mazurén", "Toberín", 5, "B72"),

    ("Las Aguas", "Museo del Oro", 4, "B74"),
    ("Museo del Oro", "Calle 19", 4, "B74"),
    ("Calle 19", "Avenida 39", 4, "B74"),
    ("Avenida 39", "Calle 45", 4, "B74"),
    ("Calle 45", "Calle 57", 4, "B74"),
    ("Calle 57", "Héroes", 4, "B74"),
    ("Héroes", "Virrey", 4, "B74"),
    ("Virrey", "Calle 127", 4, "B74"),
    ("Calle 127", "Prado", 4, "B74"),
    ("Prado", "Calle 142", 4, "B74"),
    ("Calle 142", "Calle 146", 4, "B74"),
    ("Calle 146", "Mazurén", 4, "B74"),
    ("Mazurén", "Toberín", 4, "B74"),
    ("Toberín", "Portal Norte", 4, "B74"),

    ("Portal Usme", "Molinos", 5, "B75"),
    ("Molinos", "Consuelo", 5, "B75"),
    ("Consuelo", "Socorro", 5, "B75"),
    ("Socorro", "Santa Lucía", 5, "B75"),
    ("Santa Lucía", "Fucha", 5, "B75"),
    ("Fucha", "Nariño", 5, "B75"),
    ("Nariño", "Hortúa", 5, "B75"),
    ("Hortúa", "Avenida Jiménez", 5, "B75"),
    ("Avenida Jiménez", "Avenida 39", 5, "B75"),
    ("Avenida 39", "Calle 76", 5, "B75"),
    ("Calle 76", "Héroes", 5, "B75"),
    ("Héroes", "Prado", 5, "B75"),
    ("Prado", "Calle 142", 5, "B75"),
    ("Calle 142", "Calle 146", 5, "B75"),
    ("Calle 146", "Toberín", 5, "B75"),
    ("Toberín", "Portal Norte", 5, "B75"),

    ("Portal Tunal", "Parque", 4, "C15"),
    ("Parque", "Calle 40 Sur", 4, "C15"),
    ("Calle 40 Sur", "Olaya", 4, "C15"),
    ("Olaya", "Nariño", 4, "C15"),
    ("Nariño", "Tercer Milenio", 4, "C15"),
    ("Tercer Milenio", "Avenida Jiménez", 4, "C15"),
    ("Avenida Jiménez", "Calle 19", 4, "C15"),
    ("Calle 19", "Calle 22", 4, "C15"),
    ("Calle 22", "Calle 45", 4, "C15"),
    ("Calle 45", "Calle 57", 4, "C15"),
    ("Calle 57", "Calle 76", 4, "C15"),
    ("Calle 76", "Rionegro", 4, "C15"),
    ("Rionegro", "Av. Suba Calle 116", 4, "C15"),
    ("Av. Suba Calle 116", "Humedal Córdoba", 4, "C15"),
    ("Humedal Córdoba", "Niza Calle 127", 4, "C15"),
    ("Niza Calle 127", "Gratamira", 4, "C15"),
    ("Gratamira", "Suba - Tv. 91", 4, "C15"),
    ("Suba - Tv. 91", "Portal Suba", 4, "C15"),

    ("Portal Usme", "Consuelo", 4, "C17"),
    ("Consuelo", "Santa Lucía", 4, "C17"),
    ("Santa Lucía", "Quiroga", 4, "C17"),
    ("Quiroga", "Restrepo", 4, "C17"),
    ("Restrepo", "Hortúa", 4, "C17"),
    ("Hortúa", "Guatoque - Veraguas", 4, "C17"),
    ("Guatoque - Veraguas", "Paloquemao", 4, "C17"),
    ("Paloquemao", "Avenida Eldorado", 4, "C17"),
    ("Avenida Eldorado", "Universidad Nacional", 4, "C17"),
    ("Universidad Nacional", "7 de Agosto", 4, "C17"),
    ("7 de Agosto", "San Martín", 4, "C17"),
    ("San Martín", "Suba Calle 95", 4, "C17"),
    ("Suba Calle 95", "Suba Calle 100", 4, "C17"),
    ("Suba Calle 100", "Av. Suba Calle 116", 4, "C17"),
    ("Av. Suba Calle 116", "Niza Calle 127", 4, "C17"),
    ("Niza Calle 127", "Suba - Tv. 91", 4, "C17"),
    ("Suba - Tv. 91", "La Campiña", 4, "C17"),
    ("La Campiña", "Portal Suba", 4, "C17"),

    ("Banderas", "Mandalay", 4, "C19"),
    ("Mandalay", "Marsella", 4, "C19"),
    ("Marsella", "Distrito Grafiti", 4, "C19"),
    ("Distrito Grafiti", "Zona Industrial", 4, "C19"),
    ("Zona Industrial", "Ricaurte", 4, "C19"),
    ("Ricaurte", "De La Sabana", 4, "C19"),
    ("De La Sabana", "Calle 19", 4, "C19"),
    ("Calle 19", "Calle 34", 4, "C19"),
    ("Calle 34", "Avenida 39", 4, "C19"),
    ("Avenida 39", "Suba Calle 95", 4, "C19"),
    ("Suba Calle 95", "Suba Calle 100", 4, "C19"),
    ("Suba Calle 100", "Suba Av. Boyacá", 4, "C19"),
    ("Suba Av. Boyacá", "Puente Largo", 4, "C19"),
    ("Puente Largo", "21 Ángeles", 4, "C19"),
    ("21 Ángeles", "Suba - Tv. 91", 4, "C19"),
    ("Suba - Tv. 91", "La Campiña", 4, "C19"),
    ("La Campiña", "Portal Suba", 4, "C19"),

    ("Portal 20 de Julio", "Country Sur", 5, "C25"),
    ("Country Sur", "Avenida Primero de Mayo", 5, "C25"),
    ("Avenida Primero de Mayo", "Bicentenario", 5, "C25"),
    ("Bicentenario", "Tygya - San José", 5, "C25"),
    ("Tygya - San José", "Guatoque - Veraguas", 5, "C25"),
    ("Guatoque - Veraguas", "Campín", 5, "C25"),
    ("Campín", "Movistar Arena", 5, "C25"),
    ("Movistar Arena", "Avenida Chile", 5, "C25"),
    ("Avenida Chile", "NQS Calle 75", 5, "C25"),
    ("NQS Calle 75", "San Martín", 5, "C25"),
    ("San Martín", "Suba Calle 95", 5, "C25"),
    ("Suba Calle 95", "Niza Calle 127", 5, "C25"),
    ("Niza Calle 127", "Suba Av. Boyacá", 5, "C25"),
    ("Suba Av. Boyacá", "Suba - Tv. 91", 5, "C25"),
    ("Suba - Tv. 91", "Portal Suba", 5, "C25"),

    ("Portal Sur", "Venecia", 3, "C30"),
    ("Venecia", "General Santander", 3, "C30"),
    ("General Santander", "NQS Calle 38 A Sur", 3, "C30"),
    ("NQS Calle 38 A Sur", "Santa Isabel", 3, "C30"),
    ("Santa Isabel", "CAD", 3, "C30"),
    ("CAD", "Universidad Nacional", 3, "C30"),
    ("Universidad Nacional", "Movistar Arena", 3, "C30"),
    ("Movistar Arena", "Rionegro", 3, "C30"),
    ("Rionegro", "Puente Largo", 3, "C30"),
    ("Puente Largo", "Av. Suba Calle 116", 3, "C30"),
    ("Av. Suba Calle 116", "Suba Av. Boyacá", 3, "C30"),
    ("Suba Av. Boyacá", "Suba - Tv. 91", 3, "C30"),
    ("Suba - Tv. 91", "La Campiña", 3, "C30"),
    ("La Campiña", "Portal Suba", 3, "C30"),

    ("Calle 161", "Calle 142", 4, "C50"),
    ("Calle 142", "Virrey", 4, "C50"),
    ("Virrey", "Calle 85", 4, "C50"),
    ("Calle 85", "Héroes", 4, "C50"),
    ("Héroes", "Escuela Militar", 4, "C50"),
    ("Escuela Militar", "Rionegro", 4, "C50"),
    ("Rionegro", "Puente Largo", 4, "C50"),
    ("Puente Largo", "Av. Suba Calle 116", 4, "C50"),
    ("Av. Suba Calle 116", "Suba Av. Boyacá", 4, "C50"),
    ("Suba Av. Boyacá", "21 Ángeles", 4, "C50"),
    ("21 Ángeles", "Suba - Tv. 91", 4, "C50"),
    ("Suba - Tv. 91", "La Campiña", 4, "C50"),
    ("La Campiña", "Portal Suba", 4, "C50"),

    ("Universidades", "Ciudad Universitaria", 5, "C73"),
    ("Ciudad Universitaria", "San Martín", 5, "C73"),
    ("San Martín", "Suba Calle 100", 5, "C73"),
    ("Suba Calle 100", "Niza Calle 127", 5, "C73"),
    ("Niza Calle 127", "Suba - Tv. 91", 5, "C73"),
    ("Suba - Tv. 91", "La Campiña", 5, "C73"),
    ("La Campiña", "Portal Suba", 5, "C73"),

    ("Portal Norte", "Toberín", 3, "D10"),
    ("Toberín", "Calle 146", 3, "D10"),
    ("Calle 146", "Alcalá", 3, "D10"),
    ("Alcalá", "Calle 100", 3, "D10"),
    ("Calle 100", "Calle 85", 3, "D10"),
    ("Calle 85", "Carrera 47", 3, "D10"),
    ("Carrera 47", "Carrera 53", 3, "D10"),
    ("Carrera 53", "Avenida 68", 3, "D10"),
    ("Avenida 68", "Boyacá", 3, "D10"),
    ("Boyacá", "Granja - Carrera 77", 3, "D10"),
    ("Granja - Carrera 77", "Avenida Cali", 3, "D10"),
    ("Avenida Cali", "Carrera 90", 3, "D10"),
    ("Carrera 90", "Portal 80", 3, "D10"),

    ("Portal Usme", "Molinos", 5, "D20"),
    ("Molinos", "Calle 40 Sur", 5, "D20"),
    ("Calle 40 Sur", "Restrepo", 5, "D20"),
    ("Restrepo", "Avenida Jiménez", 5, "D20"),
    ("Avenida Jiménez", "Calle 19", 5, "D20"),
    ("Calle 19", "Calle 34", 5, "D20"),
    ("Calle 34", "Calle 45", 5, "D20"),
    ("Calle 45", "Flores", 5, "D20"),
    ("Flores", "Polo", 5, "D20"),
    ("Polo", "Ferias", 5, "D20"),
    ("Ferias", "Boyacá", 5, "D20"),
    ("Boyacá", "Granja - Carrera 77", 5, "D20"),
    ("Granja - Carrera 77", "Quirigua", 5, "D20"),
    ("Quirigua", "Portal 80", 5, "D20"),

    ("Portal Tunal", "Santa Lucía", 6, "D21"),
    ("Santa Lucía", "Calle 40 Sur", 6, "D21"),
    ("Calle 40 Sur", "Fucha", 6, "D21"),
    ("Fucha", "Guatoque - Veraguas", 6, "D21"),
    ("Guatoque - Veraguas", "Ricaurte", 6, "D21"),
    ("Ricaurte", "Campín", 6, "D21"),
    ("Campín", "Movistar Arena", 6, "D21"),
    ("Movistar Arena", "7 de Agosto", 6, "D21"),
    ("7 de Agosto", "Avenida 68", 6, "D21"),
    ("Avenida 68", "Minuto de Dios", 6, "D21"),
    ("Minuto de Dios", "Granja - Carrera 77", 6, "D21"),
    ("Granja - Carrera 77", "Avenida Cali", 6, "D21"),
    ("Avenida Cali", "Carrera 90", 6, "D21"),
    ("Carrera 90", "Portal 80", 6, "D21"),

    ("Portal Sur", "Sevillana", 4, "D22"),
    ("Sevillana", "General Santander", 4, "D22"),
    ("General Santander", "Santa Isabel", 4, "D22"),
    ("Santa Isabel", "Paloquemao", 4, "D22"),
    ("Paloquemao", "Avenida Eldorado", 4, "D22"),
    ("Avenida Eldorado", "Universidad Nacional", 4, "D22"),
    ("Universidad Nacional", "Avenida Chile", 4, "D22"),
    ("Avenida Chile", "NQS Calle 75", 4, "D22"),
    ("NQS Calle 75", "Carrera 47", 4, "D22"),
    ("Carrera 47", "Avenida 68", 4, "D22"),
    ("Avenida 68", "Boyacá", 4, "D22"),
    ("Boyacá", "Minuto de Dios", 4, "D22"),
    ("Minuto de Dios", "Granja - Carrera 77", 4, "D22"),
    ("Granja - Carrera 77", "Portal 80", 4, "D22"),

    ("Universidades", "Avenida 39", 4, "D24"),
    ("Avenida 39", "Calle 57", 4, "D24"),
    ("Calle 57", "Calle 76", 4, "D24"),
    ("Calle 76", "Escuela Militar", 4, "D24"),
    ("Escuela Militar", "Carrera 47", 4, "D24"),
    ("Carrera 47", "Minuto de Dios", 4, "D24"),
    ("Minuto de Dios", "Granja - Carrera 77", 4, "D24"),
    ("Granja - Carrera 77", "Avenida Cali", 4, "D24"),
    ("Avenida Cali", "Carrera 90", 4, "D24"),
    ("Carrera 90", "Portal 80", 4, "D24"),

    ("Toberín", "Calle 161", 4, "D55"),
    ("Calle 161", "Calle 142", 4, "D55"),
    ("Calle 142", "Prado", 4, "D55"),
    ("Prado", "Pepe Sierra", 4, "D55"),
    ("Pepe Sierra", "Calle 106", 4, "D55"),
    ("Calle 106", "Virrey", 4, "D55"),
    ("Virrey", "Héroes", 4, "D55"),
    ("Héroes", "Polo", 4, "D55"),
    ("Polo", "Ferias", 4, "D55"),
    ("Ferias", "Minuto de Dios", 4, "D55"),
    ("Minuto de Dios", "Granja - Carrera 77", 4, "D55"),
    ("Granja - Carrera 77", "Avenida Cali", 4, "D55"),
    ("Avenida Cali", "Quirigua", 4, "D55"),
    ("Quirigua", "Portal 80", 4, "D55"),

    ("Portal Américas", "Transversal 86", 4, "E32"),
    ("Transversal 86", "Banderas", 4, "E32"),
    ("Banderas", "Américas - Avenida Boyacá", 4, "E32"),
    ("Américas - Avenida Boyacá", "Puente Aranda", 4, "E32"),
    ("Puente Aranda", "Zona Industrial", 4, "E32"),
    ("Zona Industrial", "Avenida Eldorado", 4, "E32"),
    ("Avenida Eldorado", "Universidad Nacional", 4, "E32"),
    ("Universidad Nacional", "7 de Agosto", 4, "E32"),
    ("7 de Agosto", "Avenida Chile", 4, "E32"),
    ("Avenida Chile", "NQS Calle 75", 4, "E32"),

    ("San Mateo", "Terreros", 3, "E42"),
    ("Terreros", "León XIII", 3, "E42"),
    ("León XIII", "La Despensa", 3, "E42"),
    ("La Despensa", "Estación Bosa", 3, "E42"),
    ("Estación Bosa", "Comuneros", 3, "E42"),
    ("Comuneros", "Paloquemao", 3, "E42"),
    ("Paloquemao", "Universidad Nacional", 3, "E42"),
    ("Universidad Nacional", "Campín", 3, "E42"),
    ("Campín", "7 de Agosto", 3, "E42"),

    ("Portal Suba", "La Campiña", 4, "F19"),
    ("La Campiña", "Suba - Tv. 91", 4, "F19"),
    ("Suba - Tv. 91", "21 Ángeles", 4, "F19"),
    ("21 Ángeles", "Suba Av. Boyacá", 4, "F19"),
    ("Suba Av. Boyacá", "Puente Largo", 4, "F19"),
    ("Puente Largo", "Suba Calle 100", 4, "F19"),
    ("Suba Calle 100", "Suba Calle 95", 4, "F19"),
    ("Suba Calle 95", "Calle 34", 4, "F19"),
    ("Calle 34", "Avenida 39", 4, "F19"),
    ("Avenida 39", "Calle 19", 4, "F19"),
    ("Calle 19", "De La Sabana", 4, "F19"),
    ("De La Sabana", "Ricaurte", 4, "F19"),
    ("Ricaurte", "Zona Industrial", 4, "F19"),
    ("Zona Industrial", "Distrito Grafiti", 4, "F19"),
    ("Distrito Grafiti", "Marsella", 4, "F19"),
    ("Marsella", "Mandalay", 4, "F19"),
    ("Mandalay", "Banderas", 4, "F19"),

    ("Las Aguas", "Museo del Oro", 4, "F23"),
    ("Museo del Oro", "Avenida Jiménez", 4, "F23"),
    ("Avenida Jiménez", "San Façon Carrera 22", 4, "F23"),
    ("San Façon Carrera 22", "Ricaurte", 4, "F23"),
    ("Ricaurte", "Puente Aranda", 4, "F23"),
    ("Puente Aranda", "Pradera", 4, "F23"),
    ("Pradera", "Américas - Avenida Boyacá", 4, "F23"),
    ("Américas - Avenida Boyacá", "Banderas", 4, "F23"),
    ("Banderas", "Biblioteca Tintal", 4, "F23"),
    ("Biblioteca Tintal", "Portal Américas", 4, "F23"),

    ("Alcalá", "Calle 127", 3, "F26"),
    ("Calle 127", "Calle 100", 3, "F26"),
    ("Calle 100", "Virrey", 3, "F26"),
    ("Virrey", "Calle 85", 3, "F26"),
    ("Calle 85", "Héroes", 3, "F26"),
    ("Héroes", "Américas - Avenida Boyacá", 3, "F26"),
    ("Américas - Avenida Boyacá", "Mandalay", 3, "F26"),
    ("Mandalay", "Banderas", 3, "F26"),
    ("Banderas", "Transversal 86", 3, "F26"),
    ("Transversal 86", "Biblioteca Tintal", 3, "F26"),
    ("Biblioteca Tintal", "Portal Américas", 3, "F26"),

    ("Portal Norte", "Calle 161", 6, "F28"),
    ("Calle 161", "Calle 146", 6, "F28"),
    ("Calle 146", "Prado", 6, "F28"),
    ("Prado", "Pepe Sierra", 6, "F28"),
    ("Pepe Sierra", "Calle 106", 6, "F28"),
    ("Calle 106", "La Castellana", 6, "F28"),
    ("La Castellana", "CDS Carrera 32", 6, "F28"),
    ("CDS Carrera 32", "Zona Industrial", 6, "F28"),
    ("Zona Industrial", "Marsella", 6, "F28"),
    ("Marsella", "Banderas", 6, "F28"),
    ("Banderas", "Biblioteca Tintal", 6, "F28"),
    ("Biblioteca Tintal", "Portal Américas", 6, "F28"),

    ("NQS Calle 75", "Avenida Chile", 4, "F32"),
    ("Avenida Chile", "7 de Agosto", 4, "F32"),
    ("7 de Agosto", "Universidad Nacional", 4, "F32"),
    ("Universidad Nacional", "Avenida Eldorado", 4, "F32"),
    ("Avenida Eldorado", "Zona Industrial", 4, "F32"),
    ("Zona Industrial", "Puente Aranda", 4, "F32"),
    ("Puente Aranda", "Américas - Avenida Boyacá", 4, "F32"),
    ("Américas - Avenida Boyacá", "Banderas", 4, "F32"),
    ("Banderas", "Transversal 86", 4, "F32"),
    ("Transversal 86", "Portal Américas", 4, "F32"),

    ("Museo Nacional", "San Diego", 4, "F51"),
    ("San Diego", "Las Nieves", 4, "F51"),
    ("Las Nieves", "Ricaurte", 4, "F51"),
    ("Ricaurte", "Distrito Grafiti", 4, "F51"),
    ("Distrito Grafiti", "Pradera", 4, "F51"),
    ("Pradera", "Marsella", 4, "F51"),
    ("Marsella", "Américas - Avenida Boyacá", 4, "F51"),
    ("Américas - Avenida Boyacá", "Mandalay", 4, "F51"),
    ("Mandalay", "Banderas", 4, "F51"),
    ("Banderas", "Biblioteca Tintal", 4, "F51"),
    ("Biblioteca Tintal", "Portal Américas", 4, "F51"),

    ("Calle 76", "Calle 45", 4, "F60"),
    ("Calle 45", "Calle 34", 4, "F60"),
    ("Calle 34", "De La Sabana", 4, "F60"),
    ("De La Sabana", "Ricaurte", 4, "F60"),
    ("Ricaurte", "Carrera 43", 4, "F60"),
    ("Carrera 43", "Banderas", 4, "F60"),
    ("Banderas", "Transversal 86", 4, "F60"),
    ("Transversal 86", "Portal Américas", 4, "F60"),

    ("Polo", "Flores", 4, "F61"),
    ("Flores", "Calle 57", 4, "F61"),
    ("Calle 57", "Avenida 39", 4, "F61"),
    ("Avenida 39", "Calle 19", 4, "F61"),
    ("Calle 19", "CDS Carrera 32", 4, "F61"),
    ("CDS Carrera 32", "Marsella", 4, "F61"),
    ("Marsella", "Banderas", 4, "F61"),
    ("Banderas", "Portal Américas", 4, "F61"),

    ("Terminal", "Calle 187", 4, "G11"),
    ("Calle 187", "Toberín", 4, "G11"),
    ("Toberín", "Calle 146", 4, "G11"),
    ("Calle 146", "Pepe Sierra", 4, "G11"),
    ("Pepe Sierra", "Calle 106", 4, "G11"),
    ("Calle 106", "Virrey", 4, "G11"),
    ("Virrey", "Calle 85", 4, "G11"),
    ("Calle 85", "Héroes", 4, "G11"),
    ("Héroes", "Escuela Militar", 4, "G11"),
    ("Escuela Militar", "Campín", 4, "G11"),
    ("Campín", "Paloquemao", 4, "G11"),
    ("Paloquemao", "Ricaurte", 4, "G11"),
    ("Ricaurte", "Santa Isabel", 4, "G11"),
    ("Santa Isabel", "NQS Calle 30 Sur", 4, "G11"),
    ("NQS Calle 30 Sur", "Alquería", 4, "G11"),
    ("Alquería", "Madelena", 4, "G11"),
    ("Madelena", "Portal Sur", 4, "G11"),

    ("Portal Norte", "Toberín", 4, "G12"),
    ("Toberín", "Calle 142", 4, "G12"),
    ("Calle 142", "Prado", 4, "G12"),
    ("Prado", "Calle 127", 4, "G12"),
    ("Calle 127", "Calle 100", 4, "G12"),
    ("Calle 100", "La Castellana", 4, "G12"),
    ("La Castellana", "NQS Calle 75", 4, "G12"),
    ("NQS Calle 75", "7 de Agosto", 4, "G12"),
    ("7 de Agosto", "Universidad Nacional", 4, "G12"),
    ("Universidad Nacional", "Avenida Eldorado", 4, "G12"),
    ("Avenida Eldorado", "Ricaurte", 4, "G12"),
    ("Ricaurte", "Comuneros", 4, "G12"),
    ("Comuneros", "General Santander", 4, "G12"),
    ("General Santander", "Perdomo", 4, "G12"),
    ("Perdomo", "Portal Sur", 4, "G12"),

    ("Portal 80", "Granja - Carrera 77", 4, "G22"),
    ("Granja - Carrera 77", "Minuto de Dios", 4, "G22"),
    ("Minuto de Dios", "Boyacá", 4, "G22"),
    ("Boyacá", "Avenida 68", 4, "G22"),
    ("Avenida 68", "Carrera 47", 4, "G22"),
    ("Carrera 47", "NQS Calle 75", 4, "G22"),
    ("NQS Calle 75", "Avenida Chile", 4, "G22"),
    ("Avenida Chile", "Universidad Nacional", 4, "G22"),
    ("Universidad Nacional", "Avenida Eldorado", 4, "G22"),
    ("Avenida Eldorado", "Paloquemao", 4, "G22"),
    ("Paloquemao", "Santa Isabel", 4, "G22"),
    ("Santa Isabel", "General Santander", 4, "G22"),
    ("General Santander", "Sevillana", 4, "G22"),
    ("Sevillana", "Portal Sur", 4, "G22"),

    ("Portal Suba", "La Campiña", 4, "G30"),
    ("La Campiña", "Suba - Tv. 91", 4, "G30"),
    ("Suba - Tv. 91", "Av. Suba Calle 116", 4, "G30"),
    ("Av. Suba Calle 116", "Puente Largo", 4, "G30"),
    ("Puente Largo", "Rionegro", 4, "G30"),
    ("Rionegro", "Movistar Arena", 4, "G30"),
    ("Movistar Arena", "Universidad Nacional", 4, "G30"),
    ("Universidad Nacional", "CAD", 4, "G30"),
    ("CAD", "Ricaurte", 4, "G30"),
    ("Ricaurte", "Santa Isabel", 4, "G30"),
    ("Santa Isabel", "NQS Calle 38 A Sur", 4, "G30"),
    ("NQS Calle 38 A Sur", "General Santander", 4, "G30"),
    ("General Santander", "Venecia", 4, "G30"),
    ("Venecia", "Portal Sur", 4, "G30"),

    ("Bicentenario", "Tygya - San José", 5, "G41"),
    ("Tygya - San José", "Guatoque - Veraguas", 5, "G41"),
    ("Guatoque - Veraguas", "NQS Calle 30 Sur", 5, "G41"),
    ("NQS Calle 30 Sur", "Alquería", 5, "G41"),
    ("Alquería", "Estación Bosa", 5, "G41"),
    ("Estación Bosa", "Terreros", 5, "G41"),
    ("Terreros", "San Mateo", 5, "G41"),

    ("7 de Agosto", "Campín", 6, "G42"),
    ("Campín", "Universidad Nacional", 6, "G42"),
    ("Universidad Nacional", "Paloquemao", 6, "G42"),
    ("Paloquemao", "Comuneros", 6, "G42"),
    ("Comuneros", "Estación Bosa", 6, "G42"),
    ("Estación Bosa", "La Despensa", 6, "G42"),
    ("La Despensa", "León XIII", 6, "G42"),
    ("León XIII", "Terreros", 6, "G42"),
    ("Terreros", "San Mateo", 6, "G42"),

    ("Portal Eldorado", "Modelia", 5, "G43"),
    ("Modelia", "Normandía", 5, "G43"),
    ("Normandía", "El Tiempo", 5, "G43"),
    ("El Tiempo", "Gobernación", 5, "G43"),
    ("Gobernación", "Quinta Paredes", 5, "G43"),
    ("Quinta Paredes", "Corferias", 5, "G43"),
    ("Corferias", "CAD", 5, "G43"),
    ("CAD", "Ricaurte", 5, "G43"),
    ("Ricaurte", "General Santander", 5, "G43"),
    ("General Santander", "Venecia", 5, "G43"),
    ("Venecia", "La Despensa", 5, "G43"),
    ("La Despensa", "León XIII", 5, "G43"),
    ("León XIII", "Terreros", 5, "G43"),
    ("Terreros", "San Mateo", 5, "G43"),

    ("Portal Sur", "Estación Bosa", 2, "G45"),
    ("Estación Bosa", "La Despensa", 2, "G45"),
    ("La Despensa", "León XIII", 2, "G45"),
    ("León XIII", "Terreros", 2, "G45"),
    ("Terreros", "San Mateo", 2, "G45"),

    ("San Mateo", "Terreros", 2, "G45"),
    ("Terreros", "León XIII", 2, "G45"),
    ("León XIII", "La Despensa", 2, "G45"),
    ("La Despensa", "Estación Bosa", 2, "G45"),
    ("Estación Bosa", "Portal Sur", 2, "G45"),

    ("Portal Norte", "Toberín", 4, "G46"),
    ("Toberín", "Alcalá", 4, "G46"),
    ("Alcalá", "Calle 100", 4, "G46"),
    ("Calle 100", "Estación Bosa", 4, "G46"),
    ("Estación Bosa", "La Despensa", 4, "G46"),
    ("La Despensa", "León XIII", 4, "G46"),
    ("León XIII", "Terreros", 4, "G46"),
    ("Terreros", "San Mateo", 4, "G46"),

    ("Museo Nacional", "San Diego", 4, "G47"),
    ("San Diego", "Las Nieves", 4, "G47"),
    ("Las Nieves", "San Victorino", 4, "G47"),
    ("San Victorino", "Tygya - San José", 4, "G47"),
    ("Tygya - San José", "Guatoque - Veraguas", 4, "G47"),
    ("Guatoque - Veraguas", "Comuneros", 4, "G47"),
    ("Comuneros", "NQS Calle 38 A Sur", 4, "G47"),
    ("NQS Calle 38 A Sur", "Sevillana", 4, "G47"),
    ("Sevillana", "Perdomo", 4, "G47"),
    ("Perdomo", "Portal Sur", 4, "G47"),

    ("Flores", "Calle 76", 5, "G52"),
    ("Calle 76", "Santa Isabel", 5, "G52"),
    ("Santa Isabel", "NQS Calle 30 Sur", 5, "G52"),
    ("NQS Calle 30 Sur", "General Santander", 5, "G52"),
    ("General Santander", "Alquería", 5, "G52"),
    ("Alquería", "Venecia", 5, "G52"),
    ("Venecia", "Madelena", 5, "G52"),
    ("Madelena", "Perdomo", 5, "G52"),
    ("Perdomo", "Portal Sur", 5, "G52"),

    ("Portal Norte", "Calle 161", 6, "H13"),
    ("Calle 161", "Mazurén", 6, "H13"),
    ("Mazurén", "Calle 146", 6, "H13"),
    ("Calle 146", "Calle 142", 6, "H13"),
    ("Calle 142", "Calle 106", 6, "H13"),
    ("Calle 106", "Calle 85", 6, "H13"),
    ("Calle 85", "Calle 76", 6, "H13"),
    ("Calle 76", "Flores", 6, "H13"),
    ("Flores", "Avenida 39", 6, "H13"),
    ("Avenida 39", "Calle 22", 6, "H13"),
    ("Calle 22", "Tercer Milenio", 6, "H13"),
    ("Tercer Milenio", "Hortúa", 6, "H13"),
    ("Hortúa", "Restrepo", 6, "H13"),
    ("Restrepo", "Quiroga", 6, "H13"),
    ("Quiroga", "Calle 40 Sur", 6, "H13"),
    ("Calle 40 Sur", "Biblioteca", 6, "H13"),
    ("Biblioteca", "Portal Tunal", 6, "H13"),

    ("Portal Suba", "Suba - Tv. 91", 5, "H15"),
    ("Suba - Tv. 91", "Gratamira", 5, "H15"),
    ("Gratamira", "Niza Calle 127", 5, "H15"),
    ("Niza Calle 127", "Humedal Córdoba", 5, "H15"),
    ("Humedal Córdoba", "Puente Largo", 5, "H15"),
    ("Puente Largo", "Rionegro", 5, "H15"),
    ("Rionegro", "Calle 76", 5, "H15"),
    ("Calle 76", "Calle 57", 5, "H15"),
    ("Calle 57", "Calle 45", 5, "H15"),
    ("Calle 45", "Calle 22", 5, "H15"),
    ("Calle 22", "Calle 19", 5, "H15"),
    ("Calle 19", "Avenida Jiménez", 5, "H15"),
    ("Avenida Jiménez", "Tercer Milenio", 5, "H15"),
    ("Tercer Milenio", "Nariño", 5, "H15"),
    ("Nariño", "Olaya", 5, "H15"),
    ("Olaya", "Calle 40 Sur", 5, "H15"),
    ("Calle 40 Sur", "Parque", 5, "H15"),
    ("Parque", "Portal Tunal", 5, "H15"),

    ("Portal Suba", "La Campiña", 4, "H17"),
    ("La Campiña", "Suba - Tv. 91", 4, "H17"),
    ("Suba - Tv. 91", "Niza Calle 127", 4, "H17"),
    ("Niza Calle 127", "Av. Suba Calle 116", 4, "H17"),
    ("Av. Suba Calle 116", "Suba Calle 100", 4, "H17"),
    ("Suba Calle 100", "Suba Calle 95", 4, "H17"),
    ("Suba Calle 95", "San Martín", 4, "H17"),
    ("San Martín", "7 de Agosto", 4, "H17"),
    ("7 de Agosto", "Universidad Nacional", 4, "H17"),
    ("Universidad Nacional", "Avenida Eldorado", 4, "H17"),
    ("Avenida Eldorado", "Paloquemao", 4, "H17"),
    ("Paloquemao", "Guatoque - Veraguas", 4, "H17"),
    ("Guatoque - Veraguas", "Hortúa", 4, "H17"),
    ("Hortúa", "Restrepo", 4, "H17"),
    ("Restrepo", "Quiroga", 4, "H17"),
    ("Quiroga", "Santa Lucía", 4, "H17"),
    ("Santa Lucía", "Consuelo", 4, "H17"),
    ("Consuelo", "Portal Usme", 4, "H17"),

    ("Portal 80", "Quirigua", 4, "H20"),
    ("Quirigua", "Granja - Carrera 77", 4, "H20"),
    ("Granja - Carrera 77", "Boyacá", 4, "H20"),
    ("Boyacá", "Ferias", 4, "H20"),
    ("Ferias", "Avenida 68", 4, "H20"),
    ("Avenida 68", "Polo", 4, "H20"),
    ("Polo", "Flores", 4, "H20"),
    ("Flores", "Calle 45", 4, "H20"),
    ("Calle 45", "Calle 34", 4, "H20"),
    ("Calle 34", "Calle 19", 4, "H20"),
    ("Calle 19", "Avenida Jiménez", 4, "H20"),
    ("Avenida Jiménez", "Restrepo", 4, "H20"),
    ("Restrepo", "Quiroga", 4, "H20"),
    ("Quiroga", "Calle 40 Sur", 4, "H20"),
    ("Calle 40 Sur", "Molinos", 4, "H20"),
    ("Molinos", "Portal Usme", 4, "H20"),

    ("Portal 80", "Carrera 90", 5, "H21"),
    ("Carrera 90", "Avenida Cali", 5, "H21"),
    ("Avenida Cali", "Granja - Carrera 77", 5, "H21"),
    ("Granja - Carrera 77", "Minuto de Dios", 5, "H21"),
    ("Minuto de Dios", "Avenida 68", 5, "H21"),
    ("Avenida 68", "7 de Agosto", 5, "H21"),
    ("7 de Agosto", "Movistar Arena", 5, "H21"),
    ("Movistar Arena", "Campín", 5, "H21"),
    ("Campín", "Ricaurte", 5, "H21"),
    ("Ricaurte", "Guatoque - Veraguas", 5, "H21"),
    ("Guatoque - Veraguas", "Fucha", 5, "H21"),
    ("Fucha", "Calle 40 Sur", 5, "H21"),
    ("Calle 40 Sur", "Santa Lucía", 5, "H21"),
    ("Santa Lucía", "Portal Tunal", 5, "H21"),

    ("Portal Norte", "Toberín", 11, "H27"),
    ("Toberín", "Calle 100", 11, "H27"),
    ("Calle 100", "Virrey", 11, "H27"),
    ("Virrey", "Calle 85", 11, "H27"),
    ("Calle 85", "Héroes", 11, "H27"),
    ("Héroes", "Calle 34", 11, "H27"),
    ("Calle 34", "Avenida Jiménez", 11, "H27"),
    ("Avenida Jiménez", "Calle 40 Sur", 11, "H27"),
    ("Calle 40 Sur", "Portal Tunal", 11, "H27"),

    ("Portal Eldorado", "Modelia", 4, "H54"),
    ("Modelia", "Avenida Rojas", 4, "H54"),
    ("Avenida Rojas", "El Tiempo", 4, "H54"),
    ("El Tiempo", "Salitre - El Greco", 4, "H54"),
    ("Salitre - El Greco", "CAN", 4, "H54"),
    ("CAN", "Quinta Paredes", 4, "H54"),
    ("Quinta Paredes", "Corferias", 4, "H54"),
    ("Corferias", "Ciudad Universitaria", 4, "H54"),
    ("Ciudad Universitaria", "Concejo de Bogotá", 4, "H54"),
    ("Concejo de Bogotá", "Hortúa", 4, "H54"),
    ("Hortúa", "Restrepo", 4, "H54"),
    ("Restrepo", "Calle 40 Sur", 4, "H54"),
    ("Calle 40 Sur", "Molinos", 4, "H54"),
    ("Molinos", "Portal Usme", 4, "H54"),

    ("Toberín", "Mazurén", 4, "H72"),
    ("Mazurén", "Alcalá", 4, "H72"),
    ("Alcalá", "Pepe Sierra", 4, "H72"),
    ("Pepe Sierra", "La Castellana", 4, "H72"),
    ("La Castellana", "Avenida Chile", 4, "H72"),
    ("Avenida Chile", "Movistar Arena", 4, "H72"),
    ("Movistar Arena", "Paloquemao", 4, "H72"),
    ("Paloquemao", "Tygya - San José", 4, "H72"),
    ("Tygya - San José", "Hospital", 4, "H72"),
    ("Hospital", "Nariño", 4, "H72"),
    ("Nariño", "Fucha", 4, "H72"),
    ("Fucha", "Olaya", 4, "H72"),
    ("Olaya", "Socorro", 4, "H72"),
    ("Socorro", "Molinos", 4, "H72"),
    ("Molinos", "Portal Usme", 4, "H72"),

    ("Toberín", "Calle 146", 6, "H73"),
    ("Calle 146", "Alcalá", 6, "H73"),
    ("Alcalá", "Prado", 6, "H73"),
    ("Prado", "Calle 127", 6, "H73"),
    ("Calle 127", "Calle 45", 6, "H73"),
    ("Calle 45", "Avenida 39", 6, "H73"),
    ("Avenida 39", "Calle 34", 6, "H73"),
    ("Calle 34", "Calle 19", 6, "H73"),
    ("Calle 19", "Fucha", 6, "H73"),
    ("Fucha", "Olaya", 6, "H73"),
    ("Olaya", "Calle 40 Sur", 6, "H73"),
    ("Calle 40 Sur", "Portal Tunal", 6, "H73"),

    ("Portal Norte", "Toberín", 4, "H75"),
    ("Toberín", "Calle 146", 4, "H75"),
    ("Calle 146", "Calle 142", 4, "H75"),
    ("Calle 142", "Prado", 4, "H75"),
    ("Prado", "Calle 100", 4, "H75"),
    ("Calle 100", "Héroes", 4, "H75"),
    ("Héroes", "Calle 76", 4, "H75"),
    ("Calle 76", "Calle 57", 4, "H75"),
    ("Calle 57", "Avenida 39", 4, "H75"),
    ("Avenida 39", "Avenida Jiménez", 4, "H75"),
    ("Avenida Jiménez", "Hortúa", 4, "H75"),
    ("Hortúa", "Nariño", 4, "H75"),
    ("Nariño", "Fucha", 4, "H75"),
    ("Fucha", "Santa Lucía", 4, "H75"),
    ("Santa Lucía", "Socorro", 4, "H75"),
    ("Socorro", "Consuelo", 4, "H75"),
    ("Consuelo", "Molinos", 4, "H75"),
    ("Molinos", "Portal Usme", 4, "H75"),

    ("Universidades", "Calle 19", 2, "H76"),
    ("Calle 19", "Avenida Jiménez", 2, "H76"),
    ("Avenida Jiménez", "Tercer Milenio", 2, "H76"),
    ("Tercer Milenio", "Restrepo", 2, "H76"),
    ("Restrepo", "Calle 40 Sur", 2, "H76"),
    ("Calle 40 Sur", "Santa Lucía", 2, "H76"),
    ("Santa Lucía", "Socorro", 2, "H76"),
    ("Socorro", "Consuelo", 2, "H76"),
    ("Consuelo", "Molinos", 2, "H76"),
    ("Molinos", "Portal Usme", 2, "H76"),

    ("Portal Américas", "Biblioteca Tintal", 4, "J23"),
    ("Biblioteca Tintal", "Banderas", 4, "J23"),
    ("Banderas", "Américas - Avenida Boyacá", 4, "J23"),
    ("Américas - Avenida Boyacá", "Pradera", 4, "J23"),
    ("Pradera", "Puente Aranda", 4, "J23"),
    ("Puente Aranda", "Ricaurte", 4, "J23"),
    ("Ricaurte", "San Façon Carrera 22", 4, "J23"),
    ("San Façon Carrera 22", "Avenida Jiménez", 4, "J23"),
    ("Avenida Jiménez", "Museo del Oro", 4, "J23"),
    ("Museo del Oro", "Las Aguas", 4, "J23"),

    ("Portal 80", "Carrera 90", 4, "J24"),
    ("Carrera 90", "Avenida Cali", 4, "J24"),
    ("Avenida Cali", "Granja - Carrera 77", 4, "J24"),
    ("Granja - Carrera 77", "Minuto de Dios", 4, "J24"),
    ("Minuto de Dios", "Carrera 47", 4, "J24"),
    ("Carrera 47", "Escuela Militar", 4, "J24"),
    ("Escuela Militar", "Calle 76", 4, "J24"),
    ("Calle 76", "Calle 57", 4, "J24"),
    ("Calle 57", "Avenida 39", 4, "J24"),
    ("Avenida 39", "Universidades", 4, "J24"),

    ("Portal Norte", "Toberín", 5, "J70"),
    ("Toberín", "Calle 146", 5, "J70"),
    ("Calle 146", "Calle 142", 5, "J70"),
    ("Calle 142", "Alcalá", 5, "J70"),
    ("Alcalá", "Prado", 5, "J70"),
    ("Prado", "Calle 127", 5, "J70"),
    ("Calle 127", "CAD", 5, "J70"),
    ("CAD", "Avenida Jiménez", 5, "J70"),
    ("Avenida Jiménez", "Museo del Oro", 5, "J70"),
    ("Museo del Oro", "Las Aguas", 5, "J70"),

    ("Portal Suba", "La Campiña", 4, "J73"),
    ("La Campiña", "Suba - Tv. 91", 4, "J73"),
    ("Suba - Tv. 91", "Niza Calle 127", 4, "J73"),
    ("Niza Calle 127", "Puente Largo", 4, "J73"),
    ("Puente Largo", "San Martín", 4, "J73"),
    ("San Martín", "Ciudad Universitaria", 4, "J73"),
    ("Ciudad Universitaria", "Centro Memoria", 4, "J73"),
    ("Centro Memoria", "Universidades", 4, "J73"),

    ("Portal Norte", "Toberín", 3, "J74"),
    ("Toberín", "Mazurén", 3, "J74"),
    ("Mazurén", "Calle 146", 3, "J74"),
    ("Calle 146", "Calle 142", 3, "J74"),
    ("Calle 142", "Prado", 3, "J74"),
    ("Prado", "Calle 127", 3, "J74"),
    ("Calle 127", "Virrey", 3, "J74"),
    ("Virrey", "Héroes", 3, "J74"),
    ("Héroes", "Calle 57", 3, "J74"),
    ("Calle 57", "Calle 45", 3, "J74"),
    ("Calle 45", "Avenida 39", 3, "J74"),
    ("Avenida 39", "Calle 19", 3, "J74"),
    ("Calle 19", "Museo Nacional", 3, "J74"),
    ("Museo Nacional", "Las Aguas", 3, "J74"),

    ("Portal Usme", "Consuelo", 3, "J76"),
    ("Consuelo", "Socorro", 3, "J76"),
    ("Socorro", "Santa Lucía", 3, "J76"),
    ("Santa Lucía", "Calle 40 Sur", 3, "J76"),
    ("Calle 40 Sur", "Restrepo", 3, "J76"),
    ("Restrepo", "Tercer Milenio", 3, "J76"),
    ("Tercer Milenio", "Avenida Jiménez", 3, "J76"),
    ("Avenida Jiménez", "Calle 19", 3, "J76"),
    ("Calle 19", "Universidades", 3, "J76"),

    ("Portal 20 de Julio", "Avenida Primero de Mayo", 4, "K10"),
    ("Avenida Primero de Mayo", "Ciudad Jardín", 4, "K10"),
    ("Ciudad Jardín", "San Bernardo", 4, "K10"),
    ("San Bernardo", "Bicentenario", 4, "K10"),
    ("Bicentenario", "Tercer Milenio", 4, "K10"),
    ("Tercer Milenio", "Avenida Jiménez", 4, "K10"),
    ("Avenida Jiménez", "Calle 22", 4, "K10"),
    ("Calle 22", "Centro Memoria", 4, "K10"),
    ("Centro Memoria", "Ciudad Universitaria", 4, "K10"),
    ("Ciudad Universitaria", "Gobernación", 4, "K10"),
    ("Gobernación", "CAN", 4, "K10"),
    ("CAN", "Salitre - El Greco", 4, "K10"),
    ("Salitre - El Greco", "Normandía", 4, "K10"),
    ("Normandía", "Modelia", 4, "K10"),
    ("Modelia", "Portal Eldorado", 4, "K10"),

    ("Terminal", "Calle 187", 3, "K16"),
    ("Calle 187", "Toberín", 3, "K16"),
    ("Toberín", "Alcalá", 3, "K16"),
    ("Alcalá", "Pepe Sierra", 3, "K16"),
    ("Pepe Sierra", "Avenida Chile", 3, "K16"),
    ("Avenida Chile", "Avenida Eldorado", 3, "K16"),
    ("Avenida Eldorado", "Corferias", 3, "K16"),
    ("Corferias", "Quinta Paredes", 3, "K16"),
    ("Quinta Paredes", "El Tiempo", 3, "K16"),
    ("El Tiempo", "Avenida Rojas", 3, "K16"),
    ("Avenida Rojas", "Modelia", 3, "K16"),
    ("Modelia", "Portal Eldorado", 3, "K16"),

    ("Alcalá", "Prado", 3, "K23"),
    ("Prado", "Calle 127", 3, "K23"),
    ("Calle 127", "Calle 85", 3, "K23"),
    ("Calle 85", "Calle 57", 3, "K23"),
    ("Calle 57", "Calle 45", 3, "K23"),
    ("Calle 45", "Calle 34", 3, "K23"),
    ("Calle 34", "Concejo de Bogotá", 3, "K23"),
    ("Concejo de Bogotá", "Ciudad Universitaria", 3, "K23"),
    ("Ciudad Universitaria", "Gobernación", 3, "K23"),
    ("Gobernación", "CAN", 3, "K23"),
    ("CAN", "Salitre - El Greco", 3, "K23"),
    ("Salitre - El Greco", "El Tiempo", 3, "K23"),
    ("El Tiempo", "Avenida Rojas", 3, "K23"),
    ("Avenida Rojas", "Portal Eldorado", 3, "K23"),

    ("San Mateo", "Terreros", 4, "K43"),
    ("Terreros", "León XIII", 4, "K43"),
    ("León XIII", "La Despensa", 4, "K43"),
    ("La Despensa", "Venecia", 4, "K43"),
    ("Venecia", "General Santander", 4, "K43"),
    ("General Santander", "Ricaurte", 4, "K43"),
    ("Ricaurte", "CAD", 4, "K43"),
    ("CAD", "Corferias", 4, "K43"),
    ("Corferias", "Quinta Paredes", 4, "K43"),
    ("Quinta Paredes", "Gobernación", 4, "K43"),
    ("Gobernación", "El Tiempo", 4, "K43"),
    ("El Tiempo", "Normandía", 4, "K43"),
    ("Normandía", "Modelia", 4, "K43"),
    ("Modelia", "Portal Eldorado", 4, "K43"),

    ("Portal Usme", "Molinos", 4, "K54 Portal Eldorado"),
    ("Molinos", "Calle 40 Sur", 4, "K54 Portal Eldorado"),
    ("Calle 40 Sur", "Restrepo", 4, "K54 Portal Eldorado"),
    ("Restrepo", "Hortúa", 4, "K54 Portal Eldorado"),
    ("Hortúa", "Concejo de Bogotá", 4, "K54 Portal Eldorado"),
    ("Concejo de Bogotá", "Ciudad Universitaria", 4, "K54 Portal Eldorado"),
    ("Ciudad Universitaria", "Corferias", 4, "K54 Portal Eldorado"),
    ("Corferias", "Quinta Paredes", 4, "K54 Portal Eldorado"),
    ("Quinta Paredes", "CAN", 4, "K54 Portal Eldorado"),
    ("CAN", "Salitre - El Greco", 4, "K54 Portal Eldorado"),
    ("Salitre - El Greco", "El Tiempo", 4, "K54 Portal Eldorado"),
    ("El Tiempo", "Avenida Rojas", 4, "K54 Portal Eldorado"),
    ("Avenida Rojas", "Modelia", 4, "K54 Portal Eldorado"),
    ("Modelia", "Portal Eldorado", 4, "K54 Portal Eldorado"),

    ("Portal Eldorado", "Modelia", 5, "L10"),
    ("Modelia", "Normandía", 5, "L10"),
    ("Normandía", "Salitre - El Greco", 5, "L10"),
    ("Salitre - El Greco", "CAN", 5, "L10"),
    ("CAN", "Gobernación", 5, "L10"),
    ("Gobernación", "Ciudad Universitaria", 5, "L10"),
    ("Ciudad Universitaria", "Centro Memoria", 5, "L10"),
    ("Centro Memoria", "Calle 22", 5, "L10"),
    ("Calle 22", "Avenida Jiménez", 5, "L10"),
    ("Avenida Jiménez", "Tercer Milenio", 5, "L10"),
    ("Tercer Milenio", "Bicentenario", 5, "L10"),
    ("Bicentenario", "San Bernardo", 5, "L10"),
    ("San Bernardo", "Ciudad Jardín", 5, "L10"),
    ("Ciudad Jardín", "Avenida Primero de Mayo", 5, "L10"),
    ("Avenida Primero de Mayo", "Portal 20 de Julio", 5, "L10"),

    ("Terminal", "Calle 187", 4, "L18"),
    ("Calle 187", "Alcalá", 4, "L18"),
    ("Alcalá", "Calle 127", 4, "L18"),
    ("Calle 127", "Pepe Sierra", 4, "L18"),
    ("Pepe Sierra", "Virrey", 4, "L18"),
    ("Virrey", "Calle 45", 4, "L18"),
    ("Calle 45", "Calle 34", 4, "L18"),
    ("Calle 34", "Tercer Milenio", 4, "L18"),
    ("Tercer Milenio", "Bicentenario", 4, "L18"),
    ("Bicentenario", "San Bernardo", 4, "L18"),
    ("San Bernardo", "Avenida Primero de Mayo", 4, "L18"),
    ("Avenida Primero de Mayo", "Country Sur", 4, "L18"),
    ("Country Sur", "Portal 20 de Julio", 4, "L18"),

    ("Portal Suba", "Suba - Tv. 91", 4, "L25"),
    ("Suba - Tv. 91", "21 Ángeles", 4, "L25"),
    ("21 Ángeles", "Suba Av. Boyacá", 4, "L25"),
    ("Suba Av. Boyacá", "Niza Calle 127", 4, "L25"),
    ("Niza Calle 127", "Suba Calle 95", 4, "L25"),
    ("Suba Calle 95", "NQS Calle 75", 4, "L25"),
    ("NQS Calle 75", "Avenida Chile", 4, "L25"),
    ("Avenida Chile", "Movistar Arena", 4, "L25"),
    ("Movistar Arena", "Campín", 4, "L25"),
    ("Campín", "Ricaurte", 4, "L25"),
    ("Ricaurte", "Guatoque - Veraguas", 4, "L25"),
    ("Guatoque - Veraguas", "Tygya - San José", 4, "L25"),
    ("Tygya - San José", "Bicentenario", 4, "L25"),
    ("Bicentenario", "Avenida Primero de Mayo", 4, "L25"),
    ("Avenida Primero de Mayo", "Country Sur", 4, "L25"),
    ("Country Sur", "Portal 20 de Julio", 4, "L25"),

    ("San Mateo", "Terreros", 5, "L41"),
    ("Terreros", "Estación Bosa", 5, "L41"),
    ("Estación Bosa", "Alquería", 5, "L41"),
    ("Alquería", "NQS Calle 30 Sur", 5, "L41"),
    ("NQS Calle 30 Sur", "Guatoque - Veraguas", 5, "L41"),
    ("Guatoque - Veraguas", "Tygya - San José", 5, "L41"),
    ("Tygya - San José", "Bicentenario", 5, "L41"),

    ("Portal Sur", "Perdomo", 3, "M47"),
    ("Perdomo", "Madelena", 3, "M47"),
    ("Madelena", "Sevillana", 3, "M47"),
    ("Sevillana", "NQS Calle 38 A Sur", 3, "M47"),
    ("NQS Calle 38 A Sur", "Comuneros", 3, "M47"),
    ("Comuneros", "Guatoque - Veraguas", 3, "M47"),
    ("Guatoque - Veraguas", "Tygya - San José", 3, "M47"),
    ("Tygya - San José", "San Victorino", 3, "M47"),
    ("San Victorino", "Las Nieves", 3, "M47"),
    ("Las Nieves", "San Diego", 3, "M47"),
    ("San Diego", "Museo Nacional", 3, "M47"),

    ("Portal Américas", "Biblioteca Tintal", 4, "M51"),
    ("Biblioteca Tintal", "Banderas", 4, "M51"),
    ("Banderas", "Mandalay", 4, "M51"),
    ("Mandalay", "Américas - Avenida Boyacá", 4, "M51"),
    ("Américas - Avenida Boyacá", "Marsella", 4, "M51"),
    ("Marsella", "Pradera", 4, "M51"),
    ("Pradera", "Distrito Grafiti", 4, "M51"),
    ("Distrito Grafiti", "Ricaurte", 4, "M51"),
    ("Ricaurte", "Las Nieves", 4, "M51"),
    ("Las Nieves", "San Diego", 4, "M51"),
    ("San Diego", "Museo Nacional", 4, "M51")
]

# Agregar nodos y conexiones al grafo
for desde, hacia, tiempo, ruta in rutas:
    grafo.agregar_nodo(desde)
    grafo.agregar_nodo(hacia)
    grafo.agregar_conexion(desde, hacia, tiempo, ruta)
    grafo.agregar_conexion(hacia, desde, tiempo, ruta)  # Conexión bidireccional

# Función para ingresar origen y destino
def obtener_origen_destino():
    origen = input("Ingrese la estación de origen: ")
    destino = input("Ingrese la estación de destino: ")
    return origen, destino

# Ejemplo de uso
origen, destino = obtener_origen_destino()
ruta, tiempo_total, rutas_nombres = a_estrella(grafo, origen, destino)
if ruta:
    print(f"La mejor ruta tiene {len(ruta) - 1} paradas.")
    print(f"Tiempo total del trayecto: {tiempo_total} minutos")
    if len(rutas_nombres) == 1:
        print(f"Ruta utilizada: {rutas_nombres[0]}")
    else:
        print("Rutas utilizadas:", " -> ".join(rutas_nombres))
        print(f"Paradas totales: {len(ruta) - 1} (usando {len(rutas_nombres)} servicios)")
    
    # Verificar si la ruta es la más accesible
    rutas_accesibles = ["1", "2", "3", "4", "5"]
    es_accesible = any(ruta[0] == estacion for estacion in rutas_accesibles)
    if es_accesible:
        print("Esta es la ruta más accesible.")
else:
    print("No se encontró una ruta entre las estaciones proporcionadas.")